apiVersion: v1
kind: Service
metadata:
  name: nginx1-service
  namespace: default
  labels:
    name: nginx1-service
    stack: frontend
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
  selector:
    name: nginx1
