{
 "title": "PowerScale Cluster Capacity",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(powerscale_cluster_total_capacity_terabytes, ClusterName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Capacity Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Capacities",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "powerscale_cluster_total_capacity_terabytes{ClusterName=~\"$ClusterName\"} - powerscale_cluster_remaining_capacity_terabytes{ClusterName=~\"$ClusterName\"}"
    },
    {
     "expr": "powerscale_cluster_total_capacity_terabytes{ClusterName=~\"$ClusterName\"}"
    },
    {
     "expr": "powerscale_directory_total_hard_quota_gigabytes{ClusterName=~\"$ClusterName\"} * powerscale_directory_total_hard_quota_percentage{ClusterName=~\"$ClusterName\"}"
    },
    {
     "expr": "powerscale_directory_total_hard_quota_gigabytes{ClusterName=~\"$ClusterName\"}"
    }
   ]
  },
  {
   "title": "Cluster Capacity Usage",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (ClusterName) (powerscale_cluster_used_capacity_percentage{ClusterName=~\"$ClusterName\"})",
     "legendFormat": "{{ClusterName}}"
    }
   ]
  },
  {
   "title": "Cluster Quota Usage",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (ClusterName) (powerscale_directory_total_hard_quota_percentage{ClusterName=~\"$ClusterName\"})",
     "legendFormat": "{{ClusterName}}"
    }
   ]
  },
  { "title": "$ClusterName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "ClusterName" },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (ClusterName) (powerscale_cluster_total_capacity_terabytes{ClusterName=~\"$ClusterName\"} - powerscale_cluster_remaining_capacity_terabytes{ClusterName=~\"$ClusterName\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (ClusterName) (powerscale_cluster_total_capacity_terabytes{ClusterName=~\"$ClusterName\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cluster Capacity Summary",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "format": "dectbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (ClusterName) (powerscale_cluster_total_capacity_terabytes{ClusterName=~\"$ClusterName\"} - powerscale_cluster_remaining_capacity_terabytes{ClusterName=~\"$ClusterName\"})",
     "legendFormat": "Used Capacity"
    },
    {
     "expr": "avg by (ClusterName) (powerscale_cluster_total_capacity_terabytes{ClusterName=~\"$ClusterName\"})",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "Cluster Quota Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (ClusterName) (powerscale_directory_total_hard_quota_gigabytes{ClusterName=~\"$ClusterName\"} * powerscale_directory_total_hard_quota_percentage{ClusterName=~\"$ClusterName\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (ClusterName) (powerscale_directory_total_hard_quota_gigabytes{ClusterName=~\"$ClusterName\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cluster Quota Summary",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (ClusterName) (powerscale_directory_total_hard_quota_gigabytes{ClusterName=~\"$ClusterName\"} * powerscale_directory_total_hard_quota_percentage{ClusterName=~\"$ClusterName\"})",
     "legendFormat": "Used Capacity"
    },
    {
     "expr": "avg by (ClusterName) (powerscale_directory_total_hard_quota_gigabytes{ClusterName=~\"$ClusterName\"})",
     "legendFormat": "Total Capacity"
    }
   ]
  }
 ]
}