apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-snapshot
  namespace: default
spec:
  storageClassName: isilon
  dataSource:
    name: snapshot-of-test-pvc
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
