apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc1
    namespace: app1
  csi:
    driver: csi-isilon.dellemc.com
    volumeAttributes:
      AccessZone: zone1
      AzServiceIP: data2.pool1.mago.corvus.com
      ClusterName: mago
      ID: "15"
      Name: csipscale-9fb5b8ba03
      Path: /ifs/data/zone1/csi/csipscale-9fb5b8ba03
      RootClientEnabled: "false"
      storage.kubernetes.io/csiProvisionerIdentity: 1718866057177-3259-csi-isilon.dellemc.com
    volumeHandle: csipscale-9fb5b8ba03=_=_=15=_=_=zone1=_=_=mago
  mountOptions:
  - vers=4.1
  - sec=sys
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mago-zone1
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: "2024-06-25T12:39:22Z"
  phase: Released
