apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc2
  namespace: app1
#Uncomment below 4 lines to set quota limit parameters
#  labels:
#    pvcSoftLimit: "10"
#    pvcAdvisoryLimit: "50"
#    pvcSoftGracePrd : "85400"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: mago-zone2
